[server]
enableStaticServing = true

[[theme.fontFaces]]
family = "Montserrat"
url = "app/static/Montserrat-Bold.ttf"
style = "bold"
weight = 700

[theme]
primaryColor = "#253EF1"
backgroundColor = "#F6F6FB"
secondaryBackgroundColor = "#13D1FC"
textColor = "#3d3a2a"
linkColor = "#0CAFFF"
borderColor = "#0CAFFF"
showWidgetBorder = true
baseRadius = "0.75rem"
buttonRadius = "full"
font = "SpaceGrotesk"
headingFontWeights = [600,500,500,500,500,500]
headingFontSizes = ["3rem", "2rem"]
codeFont = "SpaceMono"
codeFontSize = ".75rem"
codeBackgroundColor = "#ecebe4"
showSidebarBorder = true
chartCategoricalColors = ["#0ea5e9", "#059669", "#fbbf24"]

[theme.sidebar]
backgroundColor = "#253EF1"
secondaryBackgroundColor = "#ecebe3"
headingFontSizes = ["1.6rem", "1.4rem", "1.2rem"]
dataframeHeaderBackgroundColor = "#e4e4e0"